
# ==================================
# Base Configuration (အခြေခံ Configuration)
# ==================================
name = "encf"  # wrangler.jsonc က name ကို ယူသုံးထားပါတယ်။
main = "vless-proxy-worker.js"
compatibility_date = "2025-11-09"

# ==================================
# KV Namespace Binding
# ==================================
[[kv_namespaces]]
binding = "LICENSES"
id = "937967334b6c461a97e3df0c4599577e"
